eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.21.0.4:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


microservice:
  ratings-data-service:
    endpoints:
      endpoint:
        uri: http://ratings-data-service/ratingsdata/user/
  movie-info-service:
    endpoints:
      endpoint:
        uri: http://movie-info-service/movies/